version: "3.9"
services:
  php-apache:
    ports:
      - "8000:80"
    build: './build/php'
    networks:
      - db_net
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./app:/var/www/html
  # Example for MySQL docker-compose:
  #   https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
  mysql:
    build: './build/mysql'
    restart: always
    networks:
      - db_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # NOTE:
    # The above part is needed if you need persistent volume. If this part is commented-out then your data
    # from the DB will be lost in case of restart of MySQL service.
    # volumes:
    #   - dbData:/var/lib/mysql

volumes:
  app:
  dbData:

networks:
  db_net: {}


